#!/usr/bin/env node
// Builds the single prebuilt module that the package `pi.extensions` entry
// points at, so a launch does not resolve and transpile 32 TypeScript modules.
//
// Keep the `.ts` extension on the output. jiti chooses its native import path
// for a `.js` entry and its transpile path for a `.ts` entry, and only the
// transpile path resolves `@earendil-works/*` through the host's own module
// instances: a `.js` bundle running in a checkout that has devDependencies
// native-imports a second copy of Pi (measured 857-1900ms for this bundle), and
// in an install layout it fails to resolve and falls back to the transpile path
// anyway.
//
// Host-provided packages stay external; Pi resolves them for extensions (see
// Pi's docs/packages.md, "Declare dependencies").
import { readFileSync } from "node:fs";
import { build } from "esbuild";

const pkg = JSON.parse(readFileSync("package.json", "utf8"));
const externals = [
	...Object.keys(pkg.dependencies ?? {}),
	...Object.keys(pkg.peerDependencies ?? {}),
	"@earendil-works/*",
];

await build({
	entryPoints: ["src/index.ts"],
	outfile: "dist/index.ts",
	bundle: true,
	format: "esm",
	platform: "node",
	target: "node20",
	external: [...new Set(externals)],
	banner: {
		js: "// Generated by scripts/build.js from src/. Do not edit; run `npm run build`.",
	},
});
